# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_69JZBBnl7qH3uX5EPfE2B7XNl6gE2-l
"""

pip install pandas flask

def simple_chatbot(user_query):
    # Predefined financial queries and responses
    if user_query.lower() == "what is the total revenue?":
        return "The total revenue is $500,000."
    elif user_query.lower() == "how has net income changed over the last year?":
        return "The net income has increased by $20,000 over the last year."
    elif user_query.lower() == "what is the current profit margin?":
        return "The current profit margin is 24%."
    elif user_query.lower() == "what was the revenue growth last year?":
        return "The revenue growth last year was 5%."
    elif user_query.lower() == "what is the net income for the year?":
        return "The net income for the year is $120,000."
    else:
        return "Sorry, I can only provide information on predefined queries."

# Function to interact with the user
def chat():
    print("Welcome to the Financial Chatbot! Ask me about financial metrics.")
    while True:
        user_query = input("You: ")  # Ask for user input
        if user_query.lower() == "exit":  # Exit condition
            print("Goodbye!")
            break
        response = simple_chatbot(user_query)  # Get response based on input
        print("Bot:", response)  # Output the response to the user

# Run the chatbot
chat()